[package]
name = "esp-alarm-clock"
version = "0.1.0"
edition = "2024"
resolver = "2"

[[bin]]
name = "esp-alarm-clock"
harness = false

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[workspace]
members = ["crates/alarm-core", "crates/gui"]

[dependencies]
alarm-core = { path = "crates/alarm-core" }
chrono = { version = "0.4", default-features = false }
log = "0.4"
esp-idf-svc = "0.53"
chrono-tz = { version = "0.10.4", default-features = false, features = ["filter-by-regex"] }

[build-dependencies]
embuild = "0.33"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
